from enum import Enum
from typing import List

class UserRole(Enum):
    ADMIN = "Admin"
    MANAGER = "Manager"
    STAFF = "Staff"

class User:
    def __init__(self, username: str, role: UserRole):
        self._username = username
        self._role = role

    def get_username(self):
        return self._username

    def get_role(self):
        return self._role

    def can_perform_action(self, action: str) -> bool:
        permissions = {
            UserRole.ADMIN: ["add", "remove", "update", "view", "report"],
            UserRole.MANAGER: ["update", "view", "report"],
            UserRole.STAFF: ["view"]
        }
        return action in permissions.get(self._role, [])

    def __str__(self):
        return f"User: {self._username}, Role: {self._role.value}"

class AdminUser(User):
    def __init__(self, username: str):
        super().__init__(username, UserRole.ADMIN)

    def generate_full_report(self, inventory) -> str:
        report = f"=== Full Inventory Report (Generated by {self.get_username()}) ===\n"
        report += str(inventory) + "\n"
        for product in inventory.list_all_products():
            report += str(product) + "\n"
        report += f"Total Inventory Value: ${inventory.calculate_total_value():.2f}\n"
        return report